version: '2.0'

services:
  api:
    container_name: nest_api
    build: .
    ports:
      - '3000:3000'

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      - POSTGRES_DB=dbnest
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5433:5433'
